apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ayushsharma4102267/myplugin:0.1  # Replace with your private registry URL
        ports:
        - containerPort: 80
